// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

//マイグレーション設定を行うためファイル

import "dotenv/config";
import { defineConfig } from "prisma/config";

// 個別の環境変数を組み合わせて DATABASE_URL を生成する関数
const getDatabaseUrl = () => {
  // すでに DATABASE_URL がある場合はそれを使う（ローカル環境など）
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }

  // AWS環境（ECS）では個別の変数から組み立てる
  const {
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_NAME,
  } = process.env;

  // 必要な変数が揃っているかチェック
  if (DATABASE_USERNAME && DATABASE_PASSWORD && DATABASE_HOST && DATABASE_PORT && DATABASE_NAME) {
    return `postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}`;
  }

  // 環境変数が不足している場合はエラーを投げる
  throw new Error(
    'DATABASE_URL or individual database environment variables (DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME) must be set'
  );
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 組み立てたURLをセットする
    url: getDatabaseUrl(),
  },
});
